(in-package #:hi)

(defun get-eail-test-9 ()
  (list
   :number 9
   :description "Simulative Void (What happens if I delete this?)"
   :text "What happens if I delete this?"
   :eil '(:HAPPEN (:WHAT 'NIL) (:DELETE (:I '((:CASE :NOM) (:NUMBER :SING) (:PERSON :|1|) (:PRONTYPE :PRS))) (:THIS '((:NUMBER :SING) (:PRONTYPE :DEM))) '((:TENSE :PRES) (:VERBFORM :FIN) (:MARK :IF))) '((:NUMBER :SING) (:PERSON :|3|) (:TENSE :PRES) (:VERBFORM :FIN) (:PUNCT :?)))
   :eail '(∆:IMPLIES
           (∆:IMPLIES (∆:IS-A ((∆:† :I HI-ONTOLOGY:∴ 'NIL) 'NIL) (:NIL 'NIL) 'NIL)
                      (∆:IS-A ((∆:† :THIS HI-ONTOLOGY:∴ 'NIL) '((:DELETE T))) (:NIL 'NIL) 'NIL)
                      '((:DELETE T))
                      '((:MARK :IF)))
           (∆:IS-A ((∆:† :WHAT HI-ONTOLOGY:∴ 'NIL) 'NIL) (:HAPPEN HI-ONTOLOGY:∴) 'NIL)
           '((:HAPPEN HI-ONTOLOGY:∴))
           '((:PUNCT :?)))
   :sail '(∆:IMPLIES
           (∆:IMPLIES (∆:IS-A ((∆:† :I HI-ONTOLOGY:∴ 'NIL) 'NIL) (:NIL 'NIL) 'NIL)
                      (∆:IS-A ((∆:† :THIS HI-ONTOLOGY:∴ 'NIL) '((∆:√ :DELETE :DESTROY :ACTION :SYSTEM T 'NIL))) (:NIL 'NIL) 'NIL)
                      '((∆:√ :DELETE :DESTROY :ACTION :SYSTEM T 'NIL))
                      '((:MARK :IF)))
           (∆:IS-A ((∆:† :WHAT HI-ONTOLOGY:∴ 'NIL) 'NIL)
                   ((∆:√ :HAPPEN :OCCUR :STATE :MATERIAL HI-ONTOLOGY:∴ 'NIL) 'NIL)
                   'NIL)
           '((∆:√ :HAPPEN :OCCUR :STATE :MATERIAL HI-ONTOLOGY:∴ 'NIL))
           '((:PUNCT :?)))
   :facts '((FACT :I :STATUS ∴ :EPHEMERAL)
            (FACT :I :REPRESENTATION ∴ :EPHEMERAL)
            (FACT :THIS :STATUS ∴ :EPHEMERAL)
            (FACT :THIS :REPRESENTATION ∴ :EPHEMERAL)
            (FACT :WHAT :STATUS ∴ :EPHEMERAL)
            (FACT :WHAT :REPRESENTATION ∴ :EPHEMERAL)
            (FACT :DELETE :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :DELETE :FORM :ACTION :EPHEMERAL)
            (FACT :DELETE :ROOT :DESTROY :EPHEMERAL)
            (FACT :HAPPEN :PILLAR :MATERIAL :EPHEMERAL)
            (FACT :HAPPEN :FORM :STATE :EPHEMERAL)
            (FACT :HAPPEN :ROOT :OCCUR :EPHEMERAL)
            (FACT :S1 :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :S1 :FORM :STATE :EPHEMERAL)
            (FACT :S2 :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :S2 :FORM :STATE :EPHEMERAL)
            (FACT :A1 :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :A1 :FORM :BRIDGE :EPHEMERAL)
            (FACT :S3 :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :S3 :FORM :STATE :EPHEMERAL)
            (FACT :A2 :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :A2 :FORM :BRIDGE :EPHEMERAL)
            (FACT :S1 ∆:IS-A (FACT :I ∆:IS-A :NIL :EPHEMERAL) :EPHEMERAL)
            (FACT :S2 ∆:IS-A (FACT :THIS ∆:IS-A (:DELETE :DESTROY :ACTION :SYSTEM T 'NIL) :EPHEMERAL) :EPHEMERAL)
            (FACT :A1 ∆:IS-A (:DELETE :DESTROY :ACTION :SYSTEM T 'NIL) :EPHEMERAL)
            (FACT :A1 ∆:IMPLIES (:S1 :S2) :EPHEMERAL)
            (FACT :A1 :MARK :IF :EPHEMERAL)
            (FACT :S1 (:DELETE :DESTROY :ACTION :SYSTEM T 'NIL) :S2 :EPHEMERAL)
            (FACT :S3 ∆:IS-A (FACT :WHAT ∆:IS-A (:HAPPEN :OCCUR :STATE :MATERIAL ∴ 'NIL) :EPHEMERAL) :EPHEMERAL)
            (FACT :A2 ∆:IS-A (:HAPPEN :OCCUR :STATE :MATERIAL ∴ 'NIL) :EPHEMERAL)
            (FACT :A2 ∆:IMPLIES (:A1 :S3) :EPHEMERAL)
            (FACT :A2 :PUNCT :? :EPHEMERAL)
            (FACT :A1 (:HAPPEN :OCCUR :STATE :MATERIAL ∴ 'NIL) :S3 :EPHEMERAL))))