;;; =========================================
;;; AGI Thermodynamic Execution Trace [ERROR]
;;; =========================================

(:error-info
 (:message "The value
  NIL
is not of type
  HASH-TABLE"
  :backtrace
  "Backtrace for: #<SB-THREAD:THREAD tid=9755 \"hunchentoot-worker-127.0.0.1:63448\" RUNNING {70053643F3}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET \"THUNK\" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET \"THUNK\" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {1097417CB}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {700AAB5D1B}> :PACKAGE :CL)
4: (HI-LIFECYCLE::%RECOVER-FROM-METABOLIC-FAILURE #<TYPE-ERROR expected-type: HASH-TABLE datum: NIL> NIL NIL 1 #P\"/Users/micahsmith/dev/hi/log-executions/\" NIL (:TIMESTAMP 3985063520 :ONTOLOGY ((HI-FACT:FACT :SYSTEM HI-ONTOLOGY:IS-A :∆ :ABSOLUTE) (HI-FACT:FACT :MATERIAL HI-ONTOLOGY:IS-A :∆ :ABSOLUTE) (HI-FACT:FACT :CONCEPT HI-ONTOLOGY:IS-A :∆ :ABSOLUTE) (HI-FACT:FACT :USERS HI-ONTOLOGY:IS-A :SYSTEM :ABSOLUTE) (HI-FACT:FACT :SESSIONS HI-ONTOLOGY:IS-A :USERS :ABSOLUTE) (HI-FACT:FACT :IS-A HI-ONTOLOGY:IS-A :RELATION :ABSOLUTE) (HI-FACT:FACT :REQUIRES HI-ONTOLOGY:IS-A :RELATION :ABSOLUTE) (HI-FACT:FACT :IMPLIES HI-ONTOLOGY:IS-A :RELATION :ABSOLUTE) (HI-FACT:FACT :∴ HI-ONTOLOGY:IS-A :RELATION :ABSOLUTE) (HI-FACT:FACT :∆ HI-ONTOLOGY:IS-A :RELATION :ABSOLUTE) (HI-FACT:FACT :RELATION HI-ONTOLOGY:IS-A :CONCEPT :ABSOLUTE) (HI-FACT:FACT :PILLAR HI-ONTOLOGY:IS-A :CONCEPT :ABSOLUTE) ...)))
5: (HI-LIFECYCLE:STABILIZE-GRAPH)
6: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN HUNCHENSOCKET:TEXT-MESSAGE-RECEIVED))
7: ((FLET \"WITHOUT-INTERRUPTS-BODY-\" :IN SB-THREAD::CALL-WITH-MUTEX))
8: (SB-THREAD::CALL-WITH-MUTEX #<FUNCTION (FLET SB-THREAD::WITH-MUTEX-THUNK :IN HUNCHENSOCKET:TEXT-MESSAGE-RECEIVED) {10974108B}> #<SB-THREAD:MUTEX \"lock-sess-grwg4j7yj\" taken owner=hunchentoot-worker-127.0.0.1:63448>)
9: ((:METHOD HUNCHENSOCKET:TEXT-MESSAGE-RECEIVED (HI::AGI-SOCKET-RESOURCE T T)) #<unused argument> #<HUNCHENSOCKET:WEBSOCKET-CLIENT {7006050353}> \"{\\\"text\\\":\\\"what color is the sky\\\",\\\"type\\\":\\\"task_submit\\\",\\\"msg_id\\\":\\\"req-q0rc9vg4v\\\"}\") [fast-method]
10: (HUNCHENSOCKET::HANDLE-FRAME #<HI::AGI-SOCKET-RESOURCE (2 connected clients of class WEBSOCKET-CLIENT)> #<HUNCHENSOCKET:WEBSOCKET-CLIENT {7006050353}> #<HUNCHENSOCKET::FRAME {7006053113}>)
11: (HUNCHENSOCKET::READ-HANDLE-LOOP #<HI::AGI-SOCKET-RESOURCE (2 connected clients of class WEBSOCKET-CLIENT)> #<HUNCHENSOCKET:WEBSOCKET-CLIENT {7006050353}> :RFC-6455)
12: ((LAMBDA NIL :IN HUNCHENTOOT:PROCESS-REQUEST))
13: (HUNCHENSOCKET::CALL-WITH-NEW-CLIENT-FOR-RESOURCE #<HUNCHENSOCKET:WEBSOCKET-CLIENT {7006050353}> #<HI::AGI-SOCKET-RESOURCE (2 connected clients of class WEBSOCKET-CLIENT)> #<FUNCTION (LAMBDA NIL :IN HUNCHENTOOT:PROCESS-REQUEST) {700603786B}>)
14: ((SB-PCL::EMF HUNCHENTOOT:PROCESS-REQUEST) #<unused argument> #<unused argument> #<HUNCHENSOCKET::WEBSOCKET-REQUEST {7006050203}>)
15: (HUNCHENTOOT::DO-WITH-ACCEPTOR-REQUEST-COUNT-INCREMENTED #<HI::API-SERVER-ACCEPTOR (host *, port 8080)> #<FUNCTION (LAMBDA NIL :IN HUNCHENTOOT:PROCESS-CONNECTION) {7006035BDB}>)
16: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION (HUNCHENTOOT:ACCEPTOR T)) #<HI::API-SERVER-ACCEPTOR (host *, port 8080)> #<USOCKET:STREAM-USOCKET {7005198253}>) [fast-method]
17: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION :AROUND (HUNCHENTOOT:ACCEPTOR T)) #<HI::API-SERVER-ACCEPTOR (host *, port 8080)> #<USOCKET:STREAM-USOCKET {7005198253}>) [fast-method]
18: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION :AROUND (HUNCHENSOCKET:WEBSOCKET-ACCEPTOR T)) #<HI::API-SERVER-ACCEPTOR (host *, port 8080)> #<USOCKET:STREAM-USOCKET {7005198253}>) [fast-method]
19: ((:METHOD HUNCHENTOOT::HANDLE-INCOMING-CONNECTION% (HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER T)) #<HUNCHENTOOT:ONE-THREAD-PER-CONNECTION-TASKMASTER {700BA90A13}> #<USOCKET:STREAM-USOCKET {7005198253}>) [fast-method]
20: ((LABELS BORDEAUX-THREADS::%BINDING-DEFAULT-SPECIALS-WRAPPER :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
21: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
22: ((FLET \"WITHOUT-INTERRUPTS-BODY-\" :IN SB-THREAD::RUN))
23: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
24: ((FLET \"WITHOUT-INTERRUPTS-BODY-\" :IN SB-THREAD::RUN))
25: (SB-THREAD::RUN)
")
 :task-id :unknown-task :cycles 1 :history (nil))

