(in-package #:hi)

(defun get-eail-test-2 ()
  (list
   :number 2
   :description "Transitive Action Statement (Pe'il)"
   :text "John hit Bob"
   :eil '(:HIT (:JOHN '((:NUMBER :SING))) (:BOB '((:NUMBER :SING))) '((:TENSE :PAST) (:VERBFORM :FIN)))
   :eail '(∆:IMPLIES (∆:IS-A (:JOHN 'NIL) (:NIL 'NIL) 'NIL)
                     (∆:IS-A (:BOB '((:HIT T))) (:NIL 'NIL) 'NIL)
                     '((:HIT T))
                     '((:TENSE :PAST) (:VERBFORM :FIN)))
   :sail '(∆:IMPLIES
           (∆:IS-A ((∆:√ :JOHN :MALE :AGENT :MATERIAL 'NIL 'NIL) 'NIL) (:NIL 'NIL) 'NIL)
           (∆:IS-A ((∆:√ :BOB :MALE :PATIENT :MATERIAL 'NIL 'NIL) '(((∆:√ :HIT :STRIKE :ACTION :MATERIAL T 'NIL) T))) (:NIL 'NIL) 'NIL)
           '(((∆:√ :HIT :STRIKE :ACTION :MATERIAL T 'NIL) T))
           '((:TENSE :PAST) (:VERBFORM :FIN)))
   :facts '((FACT :JOHN :PILLAR :MATERIAL :EPHEMERAL)
            (FACT :JOHN :FORM :AGENT :EPHEMERAL)
            (FACT :JOHN :ROOT :MALE :EPHEMERAL)
            (FACT :BOB :PILLAR :MATERIAL :EPHEMERAL)
            (FACT :BOB :FORM :PATIENT :EPHEMERAL)
            (FACT :BOB :ROOT :MALE :EPHEMERAL)
            (FACT :HIT :PILLAR :MATERIAL :EPHEMERAL)
            (FACT :HIT :FORM :ACTION :EPHEMERAL)
            (FACT :HIT :ROOT :STRIKE :EPHEMERAL)
            (FACT :S1 :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :S1 :FORM :STATE :EPHEMERAL)
            (FACT :S2 :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :S2 :FORM :STATE :EPHEMERAL)
            (FACT :A1 :PILLAR :SYSTEM :EPHEMERAL)
            (FACT :A1 :FORM :BRIDGE :EPHEMERAL)
            (FACT :S1 ∆:IS-A (FACT :JOHN ∆:IS-A :NIL :EPHEMERAL) :EPHEMERAL)
            (FACT :S2 ∆:IS-A (FACT :BOB ∆:IS-A (:HIT :STRIKE :ACTION :MATERIAL T 'NIL) :EPHEMERAL) :EPHEMERAL)
            (FACT :A1 ∆:IS-A (:HIT :STRIKE :ACTION :MATERIAL T 'NIL) :EPHEMERAL)
            (FACT :A1 ∆:REQUIRES (:S1 :S2) :EPHEMERAL)
            (FACT :A1 :TENSE :PAST :EPHEMERAL)
            (FACT :A1 :VERBFORM :FIN :EPHEMERAL)
            (FACT :S1 (:HIT :STRIKE :ACTION :MATERIAL T 'NIL) :S2 :EPHEMERAL))))
